name: Node.js CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
        node-version: [10.x, 12.x, 14.x]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm start
      timeout-minutes: 5
